### PR TITLE
Import from unifrac repo

### PR DESCRIPTION
**Pull request by sfiligoi**
Extract the necessary files from the unifrac repo.
Adapt the support build, CI and docs.

### CODE REVIEW

**Comment by wasade** [comment]
Seems good with the code, but would it be possible to setup github actions to exercise the build and test suite?

**Comment by wasade** [comment]
...lemme see if i can get actions working as there is a config here...

**Comment by wasade** [comment]
could you merge `main`? I think that should then allow [actions](https://github.com/biocore/unifrac-binaries/actions)

**Comment by sfiligoi** [comment]
@wasade Merged in main, and the tests ran and passed.

**Pull request merged**
